FROM redis

MAINTAINER gradydong <gradydong@126.com>
LABEL Description="This image is used to start an Redis for Laravel." Vendor="gradydong" Version="1.0"

#COPY ./config/redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

CMD [ "redis-server"]   